# Generated by Django 5.0.2 on 2024-03-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='include_food_and_accommodation',
            field=models.BooleanField(default=False),
        ),
    ]
