# Generated by Django 5.0.2 on 2024-03-03 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_name_cart_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='selected_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
