# Generated by Django 5.0.2 on 2024-03-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_selected_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='cart',
            name='selected_date',
            field=models.DateField(),
        ),
    ]
