# Generated by Django 5.0.2 on 2024-03-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accnumber', models.IntegerField()),
                ('acctype', models.CharField(max_length=200)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
