# Generated by Django 5.0.2 on 2024-02-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdventurePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='adventure_package_images/')),
                ('image1', models.ImageField(upload_to='adventure_package_images/')),
                ('image2', models.ImageField(upload_to='adventure_package_images/')),
            ],
        ),
    ]
