# Generated by Django 5.0.2 on 2024-03-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='has_rated',
            field=models.BooleanField(default=False),
        ),
    ]
