# Generated by Django 5.0.2 on 2024-03-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_adventurepackage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurepackage',
            name='food_and_accommodation_price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
