# Generated by Django 5.0.2 on 2024-03-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_adventurepackage_food_and_accommodation_price_per_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventurepackage',
            name='accommodation_price_per_person',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
